version: '2'

services:
  api:
    image: k8sPOC/api
    build:
      context: ./API
      dockerfile: Dockerfile

  frontend:
    image: k8sPOC/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

