apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  labels:
    app: demo
spec:
  selector:
    app: demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-frontend-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: onvia.azurecr.io/frontend
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
      # bug? in netcore truncating symlink static file
      # hardcode the config for now
      #   volumeMounts:
      #     - name: config-volume
      #       mountPath: /app/wwwroot/config
      # volumes:
      #   - name: config-volume
      #     secret:
      #       secretName: demo-app-frontend-secret
        imagePullPolicy: Always
      imagePullSecrets:
        - name: onviacontainerreg