apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
spec:
  selector:
    app: demo
    tier: backend
  ports:
    - protocol: TCP
      port: 81
      targetPort: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-backend-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
        tier: backend
    spec:
      containers:
      - name: frontent
        image: onvia.azurecr.io/api:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: onviacontainerreg